package DAL;
// Generated 29-Dec-2014 19:31:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classificatie generated by hbm2java
 */
public class Classificatie  implements java.io.Serializable {


     private Integer id;
     private String code;
     private Set modulevoorkennises = new HashSet(0);
     private Set modules = new HashSet(0);
     private Set modules_1 = new HashSet(0);

    public Classificatie() {
    }

	
    public Classificatie(String code) {
        this.code = code;
    }
    public Classificatie(String code, Set modulevoorkennises, Set modules, Set modules_1) {
       this.code = code;
       this.modulevoorkennises = modulevoorkennises;
       this.modules = modules;
       this.modules_1 = modules_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getModulevoorkennises() {
        return this.modulevoorkennises;
    }
    
    public void setModulevoorkennises(Set modulevoorkennises) {
        this.modulevoorkennises = modulevoorkennises;
    }
    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }
    public Set getModules_1() {
        return this.modules_1;
    }
    
    public void setModules_1(Set modules_1) {
        this.modules_1 = modules_1;
    }




}


