package DAL;
// Generated 29-Dec-2014 19:31:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Integer id;
     private Classificatie classificatie;
     private int code;
     private Date begindatum;
     private Date einddatum;
     private String naam;
     private Set lesmoments = new HashSet(0);
     private Set modulevoorkennises = new HashSet(0);

    public Module() {
    }

	
    public Module(Classificatie classificatie, int code, Date begindatum, Date einddatum, String naam) {
        this.classificatie = classificatie;
        this.code = code;
        this.begindatum = begindatum;
        this.einddatum = einddatum;
        this.naam = naam;
    }
    public Module(Classificatie classificatie, int code, Date begindatum, Date einddatum, String naam, Set lesmoments, Set modulevoorkennises) {
       this.classificatie = classificatie;
       this.code = code;
       this.begindatum = begindatum;
       this.einddatum = einddatum;
       this.naam = naam;
       this.lesmoments = lesmoments;
       this.modulevoorkennises = modulevoorkennises;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Classificatie getClassificatie() {
        return this.classificatie;
    }
    
    public void setClassificatie(Classificatie classificatie) {
        this.classificatie = classificatie;
    }
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Date getBegindatum() {
        return this.begindatum;
    }
    
    public void setBegindatum(Date begindatum) {
        this.begindatum = begindatum;
    }
    public Date getEinddatum() {
        return this.einddatum;
    }
    
    public void setEinddatum(Date einddatum) {
        this.einddatum = einddatum;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Set getLesmoments() {
        return this.lesmoments;
    }
    
    public void setLesmoments(Set lesmoments) {
        this.lesmoments = lesmoments;
    }
    public Set getModulevoorkennises() {
        return this.modulevoorkennises;
    }
    
    public void setModulevoorkennises(Set modulevoorkennises) {
        this.modulevoorkennises = modulevoorkennises;
    }




}


