package DAL;
// Generated 29-Dec-2014 19:31:07 by Hibernate Tools 4.3.1



/**
 * Modulevoorkennis generated by hbm2java
 */
public class Modulevoorkennis  implements java.io.Serializable {


     private Integer id;
     private Classificatie classificatie;
     private Module module;

    public Modulevoorkennis() {
    }

    public Modulevoorkennis(Classificatie classificatie, Module module) {
       this.classificatie = classificatie;
       this.module = module;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Classificatie getClassificatie() {
        return this.classificatie;
    }
    
    public void setClassificatie(Classificatie classificatie) {
        this.classificatie = classificatie;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }




}


